### ISSUE TITLE
Dark Elf Crossbowmen Banners

### ISSUE THREAD

**Issue by khainit** [nthiebes/old-world-builder#116]
In deinem (fantastischen!) Old World Builder lässt sich bei den Repeater Crossbowmen der Dunkelelfen sowohl für den Lordling als auch für den Standartenträger eine magische Standarte auswählen, statt nur für den Standartenträger. 
Grüße aus Hamburg

**Comment by nthiebes** [comment]
Moin, danke, sollte jetzt schon angepasst sein! 👍

Grüße zurück von Hamburg nach Hamburg 😄
