### ISSUE TITLE
Add Label for "General" & "BSB" on Unit Overview

### ISSUE THREAD

**Issue by CihanBlinzelt** [nthiebes/old-world-builder#134]
As a User I want to easily see which character my general or BSB is so I dont need to look through the character equipment

![image](https://github.com/nthiebes/old-world-builder/assets/1200072/0ec07aa2-7b73-430b-8f7e-9609db20deb7)

**Comment by nthiebes** [comment]
Should already exist for all armies by now. If you spot a missing option, please let me know 👍.
