### ISSUE TITLE
Rework List Creation View

### ISSUE THREAD

**Issue by CihanBlinzelt** [nthiebes/old-world-builder#135]
As a User I want to create lists as fast and thoughtless as possible.

Suggestions:
- Naming a list should be optional
- If a list doesnt have a set name, then it automatically uses "Faction, Points, Date" as template
- The pts input field requires me to actually type in the points. Dropdowns are easier to use
- Get rid of the "Warhammer"-Label entirely. Nobody uses this tool for old lists. If so, you can also get rid of the The Old World logo, since there are no other options. This makes the army list creation way faster

![image](https://github.com/nthiebes/old-world-builder/assets/1200072/86e1ba32-ab74-438c-a962-a371582ccc50)

**Comment by nthiebes** [comment]
Thank you! 🙏 Some of your suggested changes are included in the latest update.
