### ISSUE TITLE
Demons of chaos core units should be playable as Special

### ISSUE THREAD

**Issue by lancedolan** [nthiebes/old-world-builder#144]
Per ToW rules, units like daemonettes and blood letters may be fielded as core OR special, depending on who the general is. 

Example: Herald of Khorne as general causes blood letters to become core, while daemonettes would be Special in that same army

This is currently preventing me using the app for my army 😝

Old world builder does track who the general is, so this shouldn't require new inputs; the armies just need to be addable to core or special. Bonus points if you HIDE them as an option from where they'd be invalid once the general is known.

**Comment by nthiebes** [comment]
Thanks for reporting this! 🙏

I added all units to core and special, and also filled out the notes. I won't get any bonus points though, validation for army rules will follow later :).

**Comment by lancedolan** [comment]
Wow that was fast for an open source project!
