### ISSUE TITLE
Add a points counter in "game view"

### ISSUE THREAD

**Issue by rafparis** [nthiebes/old-world-builder#149]
Add a points killed counter when you are in game view, to calculate 50%, 25% and destroyed for victory points. (like Launch Bay Next for Xwing have).
It can be a set of 4 buttons (0, 50%, 25%, 100%), or a button that toggles between these sates, and a counter that is sticked on top or bottom. Maybe add options to add "general death", "captured banners", "captured army banner", "BSB killed"
I can help with the Ui/UX if needed :)

**Comment by nthiebes** [comment]
Sweet idea! 🙌 If you like, you can make a UX proposal 👍.

**Comment by rafparis** [comment]
> Sweet idea! 🙌 If you like, you can make a UX proposal 👍.

sure :) do you have a link to a figma file of the project or were you doing it on the fly?

**Comment by rafparis** [comment]
Ok, nevermind, here is a fast mockup:
![ux-1](https://github.com/nthiebes/old-world-builder/assets/1112513/ebda19dd-ae6e-4e76-8c6f-852739fce985)
![ux-2](https://github.com/nthiebes/old-world-builder/assets/1112513/f2d2d80b-b5a6-4e51-a2b1-0e88c875f3e7)
The victopry points for the general and the additional points for the BSB can be calculated automatically, since you define who is the general and the BSB.
Rest of the rules for VPs:
Victory Points are won in several ways:
Dead or Fled: The most usual way to win Victory Points is
by destroying, routing or significantly reducing the fighting
strength of enemy units:
• Each enemy unit that has been destroyed or that has fled
off the battlefield is worth a number of Victory Points
equal to 100% of its points cost.
• Each enemy unit that is fleeing at the end of the battle is
worth a number of Victory Points equal to 50% of its points
cost (rounding fractions up). For example, a unit that cost
your opponent 351 points to field would be worth 176
Victory Points to you if it is fleeing when the battle ends.
• Each enemy unit that has been reduced to less than 25% of
its starting Unit Strength at the end of the battle is worth
a number of Victory Points equal to 25% of its points cost
(rounding fractions up).
The King is Dead: If the enemy General is slain, has fled off
the battlefield or is fleeing when the game ends, you win a
bonus of 100 Victory Points.
Trophies of War: You win a bonus of 50 Victory Points for
every enemy standard claimed as a trophy, as described on
page 200. Additionally, if the enemy Battle Standard Bearer
is slain, has fled off the battlefield or is fleeing when the game
ends, you win another bonus of 50 Victory Points.
Scenario Objectives: Some scenario special rules give special
objectives to complete. Should you do so, you win a Victory
Points bonus, as described in the scenario.
Special Features: If the players have agreed to the inclusion
of a special feature, or if the scenario specifies one must be
included, the player that controls it at the end of the battle will
win a Victory Points bonus, as described in the feature’s special
rules and/or as described in the scenario.

**Comment by nthiebes** [comment]
Wazup! 👋 Thanks for your mockup! I didn't have the time yet to properly reply, but I already started the implementation. It would have been useful for a tournament I visited this weekend, but I didn't finish the feature in time 🤷‍♂️.

**Comment by nthiebes** [comment]
Done and live! 🙌
