### ISSUE TITLE
List creation/immediate delete bug

### ISSUE THREAD

**Issue by tom-gall** [nthiebes/old-world-builder#157]
On Safari on Mac (doesn't happen on Chrome on Mac) when creating a list, the minute you hit return to create the list a dialog will pop up asking if you want to delete the list. The dialog is not able to be dismissed. Cancel/X box, will not cause dialog to go away. You can still interact and create the list behind the dialog but it's really annoying!

**Comment by nthiebes** [comment]
Thanks for reporting this! Unfortunately, I cannot reproduce it yet. Could you describe your steps a bit closer or even better record a video?

**Comment by nthiebes** [comment]
Let me know if you can still reproduce the behavior with the latest version. For now, I'll close this issue.
