### ISSUE TITLE
Add unit stats in view unit

### ISSUE THREAD

**Issue by rafparis** [nthiebes/old-world-builder#160]
i find myself going a lot to "game mode" and scroll a lot, just because i want to verify a stat for a unit :)
So it would be nice to have also the stats on the unit column, like this:
![image](https://github.com/nthiebes/old-world-builder/assets/1112513/ddb4bdbb-0f24-488b-9257-e199cac98420)

**Comment by nthiebes** [comment]
Hey hey, you can just click the icon next to the name of a unit to see all stats and the full unit profile 👍.
