### ISSUE TITLE
minor GUI correction

### ISSUE THREAD

**Issue by rafparis** [nthiebes/old-world-builder#163]
![image](https://github.com/nthiebes/old-world-builder/assets/1112513/60841a1c-e9e7-4529-8ef5-9b360ccb0941)
set the width of the modal to hug the window content, so we don't have the horizontal scroll from the stats table :)

**Comment by nthiebes** [comment]
Unfortunately, I can't make the width to auto adjust since the content is inside an iframe. I increased the width a bit more. Anything beyond that and it will look weird when there is less content in the modal.
