### ISSUE TITLE
High Elf Mages (with honors) cannot equip magical armor

### ISSUE THREAD

**Issue by angryalbatross** [nthiebes/old-world-builder#181]
High Elf Mages that have the following titles should be able to equip magical armor via the Ithilimar Armor or Dragon Armor special rules

- Warden of Saphery
- Blood of Caledor

At least I think this is correct?  Blood of Caledor definitely cause you get the plate armor for free.

**Comment by davedowns** [comment]
Warden of Saphery at least doesn't allow ages to buy magic armour, according to the Forces of Fantasy FAQ.

**Comment by TheFakeCake** [comment]
The [Ithilmar Armour](https://tow.whfb.app/special-rules/ithilmar-armour-ithilmar-barding) and [Dragon Armour](https://tow.whfb.app/special-rules/dragon-armour) special rules only allow wizards to cast spell while wearing armor (they remove the penalty) among other things.
They don't give a character any armour options..

The [Blood of Caledor](https://tow.whfb.app/magic-item/blood-of-caledor) honor gives the full plate armor option and the Dragon Armour special rule.
Thus, a Mage having this elven honor can be equipped with a magic armour and he won't be subject to the spell casting penalty.

**Comment by angryalbatross** [comment]
Awww lame!

Very Respectfully,
Dan Burgett
817-709-6008
***@***.***

**Comment by nthiebes** [comment]
Done!
