### ISSUE TITLE
0-1 per 1000 points is not applied

### ISSUE THREAD

**Issue by Panzerbjrn** [nthiebes/old-world-builder#182]
For example, I can add as many Helblasters to my army as I want (Within the points limit) despite it being 0-1 per 1000 points.

There should be a notice when trying to add more than allowed, similar to when you go over your points limit.

Example from a 1500 points list:
![2024-05-23 12_23_38-Old World Builder _ Empire of Man](https://github.com/nthiebes/old-world-builder/assets/10132417/7798c363-d6b8-47fd-b797-b234be875b25)

**Comment by nthiebes** [comment]
Hey, thanks! We already have an issue for that: https://github.com/nthiebes/old-world-builder/issues/73

**Comment by Panzerbjrn** [comment]
Good stuff, I had a look, but didn't realise this one ws the same based on the subject. Thanks.
