### ISSUE TITLE
Magic items not showing: The old world

### ISSUE THREAD

**Issue by QuintinHoare** [nthiebes/old-world-builder#67]
Magic items are not showing in the third window when selecting a character.

The option for magic items is not showing. The roster just has the points missing that was spent on magic items.
![image](https://github.com/nthiebes/old-world-builder/assets/156649261/1df95048-a3ff-4cc0-81b8-9759f544e0be)

**Comment by nthiebes** [comment]
Thanks for reporting! Some armies lost access to magic items for now since we had to change the data structure. Most armies are already up-and-running again, and the others should follow soonish 💪.

**Comment by nthiebes** [comment]
Should be available now.
